--------------------------------------------------------
--  파일이 생성됨 - 토요일-4월-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table P_MEMBER
--------------------------------------------------------

  CREATE TABLE "CONNECTJOB"."P_MEMBER" 
   (	"P_ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"P_NAME" VARCHAR2(100 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"IS_SNS" VARCHAR2(30 BYTE), 
	"ENROLL_DATE" DATE DEFAULT SYSDATE, 
	"EMAIL_CONFIRM" VARCHAR2(20 BYTE) DEFAULT 'Y', 
	"KAKAO_ID" NUMBER, 
	"GOOGLE_ID" VARCHAR2(255 BYTE), 
	"NAVER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CONNECTJOB.P_MEMBER
SET DEFINE OFF;
Insert into CONNECTJOB.P_MEMBER (P_ID,PASSWORD,P_NAME,GENDER,PHONE,IS_SNS,ENROLL_DATE,EMAIL_CONFIRM,KAKAO_ID,GOOGLE_ID,NAVER_ID) values ('sihus@naver.com','$2a$10$Rr2YxTggIGNPkn3DPD9G9.uY1sA6eeNJEEyb9M5YRerKO6Rtv4czG','박성화','M','01025757939','kakao',to_date('19/04/13','RR/MM/DD'),'Y',1056898727,null,null);
Insert into CONNECTJOB.P_MEMBER (P_ID,PASSWORD,P_NAME,GENDER,PHONE,IS_SNS,ENROLL_DATE,EMAIL_CONFIRM,KAKAO_ID,GOOGLE_ID,NAVER_ID) values ('sihus0928@gmail.com','$2a$10$VcuanIclwn40BOj0R0mUzettXi/zVolYDxJa5hwQtOdbouG6IqlcK','박성화(구글)','M','01025757939','google',to_date('19/04/13','RR/MM/DD'),'Y',null,'111901456619683660000',null);
Insert into CONNECTJOB.P_MEMBER (P_ID,PASSWORD,P_NAME,GENDER,PHONE,IS_SNS,ENROLL_DATE,EMAIL_CONFIRM,KAKAO_ID,GOOGLE_ID,NAVER_ID) values ('sihus2@naver.com','$2a$10$X.mJBzUr/DGp8z092v3e5usXufHS10HTnpFUf.LnEEZxitfpSlrhq','Sihus','M','01025757939','naver',to_date('19/04/13','RR/MM/DD'),'Y',null,null,71544448);
--------------------------------------------------------
--  DDL for Index SYS_C007574
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONNECTJOB"."SYS_C007574" ON "CONNECTJOB"."P_MEMBER" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table P_MEMBER
--------------------------------------------------------

  ALTER TABLE "CONNECTJOB"."P_MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CONNECTJOB"."P_MEMBER" MODIFY ("P_NAME" NOT NULL ENABLE);
  ALTER TABLE "CONNECTJOB"."P_MEMBER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "CONNECTJOB"."P_MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "CONNECTJOB"."P_MEMBER" ADD PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
